pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
                echo 'Code récupéré depuis GitHub'
            }
        }

        stage('Check project structure') {
            steps {
                sh 'ls -la'
                sh 'ls -la bresil'
                sh 'ls -la colombie'
                sh 'ls -la equateur'
                sh 'ls -la siege'
                sh 'ls -la FrontEnd'
                sh 'ls -la Tests'
                sh 'ls -la jenkins'
            }
        }

        stage('Check tests files') {
            steps {
                sh 'test -f Tests/bresil/test_statut_lot.py'
                sh 'test -f Tests/colombie/test_statut_lot.py'
                sh 'test -f Tests/equateur/test_statut_lot.py'

                echo 'Fichiers de tests présents pour les 3 pays'
            }
        }

        stage('Run Python tests') {
            steps {
                sh '''
                    python3 --version
                    pip3 --version

                    pip3 install --break-system-packages pytest requests paho-mqtt psycopg2-binary

                    python3 Tests/bresil/test_statut_lot.py
                    python3 Tests/colombie/test_statut_lot.py
                    python3 Tests/equateur/test_statut_lot.py
                '''

                echo 'Tests Python exécutés pour les 3 pays'
            }
        }

        stage('Validate compose files') {
            steps {
                sh 'find . -name "docker-compose.yml"'
                sh 'find . -name "docker-compose.yml" | grep -q docker-compose.yml'

                echo 'Fichiers docker-compose détectés'
            }
        }

        stage('Archive project info') {
            steps {
                sh 'find . -maxdepth 3 -type f > project_files.txt'
                archiveArtifacts artifacts: 'project_files.txt', fingerprint: true
            }
        }
    }

    post {
        always {
            echo 'Pipeline terminée'
        }

        success {
            echo 'Pipeline réussie'
        }

        failure {
            echo 'La pipeline a échoué'
        }
    }
}