pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Code récupéré depuis GitHub'
            }
        }

        stage('Check project structure') {
            steps {
                sh 'ls -la'
                sh 'ls -la bresil'
                sh 'ls -la colombie'
                sh 'ls -la equateur'
                sh 'ls -la siege'
                sh 'ls -la jenkins'
            }
        }

        stage('Validate compose files') {
            steps {
                sh 'find . -name "docker-compose.yml"'
            }
        }

        stage('Archive project info') {
            steps {
                sh 'find . -maxdepth 2 -type f > project_files.txt'
                archiveArtifacts artifacts: 'project_files.txt', fingerprint: true
            }
        }
    }
}